name: os-builds

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: brew install cairo pango gdk-pixbuf libffi
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Cache python modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ hashFiles('requirements.txt') }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pkg-deps-${{ hashFiles('requirements.txt') }}-
            ${{ runner.os }}-pkg-deps-
            ${{ runner.os }}-
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tf] --upgrade
      - name: Run analysis script
        run: |
          wget https://github.com/mindee/doctr/releases/download/v0.1.0/sample.pdf
          python scripts/analyze.py sample.pdf --noblock

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Cache python modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ hashFiles('requirements.txt') }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pkg-deps-${{ hashFiles('requirements.txt') }}-
            ${{ runner.os }}-pkg-deps-
            ${{ runner.os }}-
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tf] --upgrade
